baseURL = 'https://just-so-yummy.de/'
languageCode = 'de-de'
title = 'Rezepte'
theme = "etch"

[taxonomies]
  category = "categories"

[params]
  description = "Leckere Rezepte zum Nachkochen"
  author = "Just So Yummy"
  contact = "Contact: Jonas Sander, jonas.sander(at)t-online.de"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"