baseURL = 'https://just-so-yummy.de/'
theme = "etch"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

[taxonomies]
  category = "categories"

[params]
  author = "Just So Yummy"
  contact = "Contact: Jonas Sander, jonas.sander(at)t-online.de"
  dark = "auto"
  highlight = true

[languages]
  [languages.de]
    locale = 'de-de'
    label = 'Deutsch'
    weight = 1
    title = 'Rezepte'
    [languages.de.params]
      description = "Leckere Rezepte zum Nachkochen"

  [languages.en]
    locale = 'en-us'
    label = 'English'
    weight = 2
    title = 'Recipes'
    [languages.en.params]
      description = "Delicious recipes to cook at home"

[permalinks]
  posts = "/:title/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"